#pragma once

enum ObjectFields {
    eObjectFieldGuid = 0x0000,     // Size: 2, Type: LONG, Flags: PUBLIC
    eObjectFieldType = 0x0002,     // Size: 1, Type: INT, Flags: PUBLIC
    eObjectFieldEntry = 0x0003,    // Size: 1, Type: INT, Flags: PUBLIC
    eObjectFieldScaleX = 0x0004,   // Size: 1, Type: FLOAT, Flags: PUBLIC
    eObjectFieldPadding = 0x0005,  // Size: 1, Type: INT, Flags: NONE
    eObjectEnd = 0x0006,
};

enum ItemFields {
    eItemFieldOwner = eObjectEnd + 0x0000,               // Size: 2, Type: LONG, Flags: PUBLIC
    eItemFieldContained = eObjectEnd + 0x0002,           // Size: 2, Type: LONG, Flags: PUBLIC
    eItemFieldCreator = eObjectEnd + 0x0004,             // Size: 2, Type: LONG, Flags: PUBLIC
    eItemFieldGiftcreator = eObjectEnd + 0x0006,         // Size: 2, Type: LONG, Flags: PUBLIC
    eItemFieldStackCount = eObjectEnd + 0x0008,          // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
    eItemFieldDuration = eObjectEnd + 0x0009,            // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
    eItemFieldSpellCharges = eObjectEnd + 0x000A,        // Size: 5, Type: INT, Flags: OWNER, ITEM_OWNER
    eItemFieldFlags = eObjectEnd + 0x000F,               // Size: 1, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment11 = eObjectEnd + 0x0010,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment13 = eObjectEnd + 0x0012,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment21 = eObjectEnd + 0x0013,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment23 = eObjectEnd + 0x0015,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment31 = eObjectEnd + 0x0016,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment33 = eObjectEnd + 0x0018,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment41 = eObjectEnd + 0x0019,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment43 = eObjectEnd + 0x001B,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment51 = eObjectEnd + 0x001C,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment53 = eObjectEnd + 0x001E,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment61 = eObjectEnd + 0x001F,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment63 = eObjectEnd + 0x0021,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment71 = eObjectEnd + 0x0022,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment73 = eObjectEnd + 0x0024,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment81 = eObjectEnd + 0x0025,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment83 = eObjectEnd + 0x0027,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment91 = eObjectEnd + 0x0028,       // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment93 = eObjectEnd + 0x002A,       // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment101 = eObjectEnd + 0x002B,      // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment103 = eObjectEnd + 0x002D,      // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment111 = eObjectEnd + 0x002E,      // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment113 = eObjectEnd + 0x0030,      // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldEnchantment121 = eObjectEnd + 0x0031,      // Size: 2, Type: INT, Flags: PUBLIC
    eItemFieldEnchantment123 = eObjectEnd + 0x0033,      // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    eItemFieldPropertySeed = eObjectEnd + 0x0034,        // Size: 1, Type: INT, Flags: PUBLIC
    eItemFieldRandomPropertiesId = eObjectEnd + 0x0035,  // Size: 1, Type: INT, Flags: PUBLIC
    eItemFieldDurability = eObjectEnd + 0x0036,          // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
    eItemFieldMaxdurability = eObjectEnd + 0x0037,       // Size: 1, Type: INT, Flags: OWNER, ITEM_OWNER
    eItemFieldCreatePlayedTime = eObjectEnd + 0x0038,    // Size: 1, Type: INT, Flags: PUBLIC
    eItemFieldPad = eObjectEnd + 0x0039,                 // Size: 1, Type: INT, Flags: NONE
    eItemEnd = eObjectEnd + 0x003A,
};

enum ContainerFields {
    eContainerFieldNumSlots = eItemEnd + 0x0000,  // Size: 1, Type: INT, Flags: PUBLIC
    eContainerAlignPad = eItemEnd + 0x0001,       // Size: 1, Type: BYTES, Flags: NONE
    eContainerFieldSlot1 = eItemEnd + 0x0002,     // Size: 72, Type: LONG, Flags: PUBLIC
    eContainerEnd = eItemEnd + 0x004A,
};

enum UnitFields {
    eUnitFieldCharm = eObjectEnd + 0x0000,                              // Size: 2, Type: LONG, Flags: PUBLIC
    eUnitFieldSummon = eObjectEnd + 0x0002,                             // Size: 2, Type: LONG, Flags: PUBLIC
    eUnitFieldCritter = eObjectEnd + 0x0004,                            // Size: 2, Type: LONG, Flags: PRIVATE
    eUnitFieldCharmedby = eObjectEnd + 0x0006,                          // Size: 2, Type: LONG, Flags: PUBLIC
    eUnitFieldSummonedby = eObjectEnd + 0x0008,                         // Size: 2, Type: LONG, Flags: PUBLIC
    eUnitFieldCreatedby = eObjectEnd + 0x000A,                          // Size: 2, Type: LONG, Flags: PUBLIC
    eUnitFieldTarget = eObjectEnd + 0x000C,                             // Size: 2, Type: LONG, Flags: PUBLIC
    eUnitFieldChannelObject = eObjectEnd + 0x000E,                      // Size: 2, Type: LONG, Flags: PUBLIC
    eUnitChannelSpell = eObjectEnd + 0x0010,                            // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldBytes0 = eObjectEnd + 0x0011,                             // Size: 1, Type: BYTES, Flags: PUBLIC
    eUnitFieldHealth = eObjectEnd + 0x0012,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPoweR1 = eObjectEnd + 0x0013,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPoweR2 = eObjectEnd + 0x0014,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPoweR3 = eObjectEnd + 0x0015,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPoweR4 = eObjectEnd + 0x0016,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPoweR5 = eObjectEnd + 0x0017,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPoweR6 = eObjectEnd + 0x0018,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPoweR7 = eObjectEnd + 0x0019,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMaxhealth = eObjectEnd + 0x001A,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMaxpoweR1 = eObjectEnd + 0x001B,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMaxpoweR2 = eObjectEnd + 0x001C,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMaxpoweR3 = eObjectEnd + 0x001D,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMaxpoweR4 = eObjectEnd + 0x001E,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMaxpoweR5 = eObjectEnd + 0x001F,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMaxpoweR6 = eObjectEnd + 0x0020,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMaxpoweR7 = eObjectEnd + 0x0021,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPowerRegenFlatModifier = eObjectEnd + 0x0022,             // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
    eUnitFieldPowerRegenInterruptedFlatModifier = eObjectEnd + 0x0029,  // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
    eUnitFieldLevel = eObjectEnd + 0x0030,                              // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldFactiontemplate = eObjectEnd + 0x0031,                    // Size: 1, Type: INT, Flags: PUBLIC
    eUnitVirtualItemSlotId = eObjectEnd + 0x0032,                       // Size: 3, Type: INT, Flags: PUBLIC
    eUnitFieldFlags = eObjectEnd + 0x0035,                              // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldFlags2 = eObjectEnd + 0x0036,                             // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldAurastate = eObjectEnd + 0x0037,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldBaseattacktime = eObjectEnd + 0x0038,                     // Size: 2, Type: INT, Flags: PUBLIC
    eUnitFieldRangedattacktime = eObjectEnd + 0x003A,                   // Size: 1, Type: INT, Flags: PRIVATE
    eUnitFieldBoundingradius = eObjectEnd + 0x003B,                     // Size: 1, Type: FLOAT, Flags: PUBLIC
    eUnitFieldCombatreach = eObjectEnd + 0x003C,                        // Size: 1, Type: FLOAT, Flags: PUBLIC
    eUnitFieldDisplayid = eObjectEnd + 0x003D,                          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldNativedisplayid = eObjectEnd + 0x003E,                    // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMountdisplayid = eObjectEnd + 0x003F,                     // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldMindamage = eObjectEnd + 0x0040,         // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
    eUnitFieldMaxdamage = eObjectEnd + 0x0041,         // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
    eUnitFieldMinoffhanddamage = eObjectEnd + 0x0042,  // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
    eUnitFieldMaxoffhanddamage = eObjectEnd + 0x0043,  // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER, PARTY_LEADER
    eUnitFieldBytes1 = eObjectEnd + 0x0044,            // Size: 1, Type: BYTES, Flags: PUBLIC
    eUnitFieldPetnumber = eObjectEnd + 0x0045,         // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPetNameTimestamp = eObjectEnd + 0x0046,  // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldPetexperience = eObjectEnd + 0x0047,     // Size: 1, Type: INT, Flags: OWNER
    eUnitFieldPetnextlevelexp = eObjectEnd + 0x0048,   // Size: 1, Type: INT, Flags: OWNER
    eUnitDynamicFlags = eObjectEnd + 0x0049,           // Size: 1, Type: INT, Flags: DYNAMIC
    eUnitModCastSpeed = eObjectEnd + 0x004A,           // Size: 1, Type: FLOAT, Flags: PUBLIC
    eUnitCreatedBySpell = eObjectEnd + 0x004B,         // Size: 1, Type: INT, Flags: PUBLIC
    eUnitNpcFlags = eObjectEnd + 0x004C,               // Size: 1, Type: INT, Flags: DYNAMIC
    eUnitNpcEmotestate = eObjectEnd + 0x004D,          // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldStaT0 = eObjectEnd + 0x004E,             // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldStaT1 = eObjectEnd + 0x004F,             // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldStaT2 = eObjectEnd + 0x0050,             // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldStaT3 = eObjectEnd + 0x0051,             // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldStaT4 = eObjectEnd + 0x0052,             // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldPosstaT0 = eObjectEnd + 0x0053,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldPosstaT1 = eObjectEnd + 0x0054,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldPosstaT2 = eObjectEnd + 0x0055,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldPosstaT3 = eObjectEnd + 0x0056,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldPosstaT4 = eObjectEnd + 0x0057,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldNegstaT0 = eObjectEnd + 0x0058,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldNegstaT1 = eObjectEnd + 0x0059,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldNegstaT2 = eObjectEnd + 0x005A,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldNegstaT3 = eObjectEnd + 0x005B,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldNegstaT4 = eObjectEnd + 0x005C,          // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldResistances = eObjectEnd + 0x005D,       // Size: 7, Type: INT, Flags: PRIVATE, OWNER, PARTY_LEADER
    eUnitFieldResistancebuffmodspositive = eObjectEnd + 0x0064,   // Size: 7, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldResistancebuffmodsnegative = eObjectEnd + 0x006B,   // Size: 7, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldBaseMana = eObjectEnd + 0x0072,                     // Size: 1, Type: INT, Flags: PUBLIC
    eUnitFieldBaseHealth = eObjectEnd + 0x0073,                   // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldBytes2 = eObjectEnd + 0x0074,                       // Size: 1, Type: BYTES, Flags: PUBLIC
    eUnitFieldAttackPower = eObjectEnd + 0x0075,                  // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldAttackPowerMods = eObjectEnd + 0x0076,              // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
    eUnitFieldAttackPowerMultiplier = eObjectEnd + 0x0077,        // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    eUnitFieldRangedAttackPower = eObjectEnd + 0x0078,            // Size: 1, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldRangedAttackPowerMods = eObjectEnd + 0x0079,        // Size: 1, Type: TWO_SHORT, Flags: PRIVATE, OWNER
    eUnitFieldRangedAttackPowerMultiplier = eObjectEnd + 0x007A,  // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    eUnitFieldMinrangeddamage = eObjectEnd + 0x007B,              // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    eUnitFieldMaxrangeddamage = eObjectEnd + 0x007C,              // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    eUnitFieldPowerCostModifier = eObjectEnd + 0x007D,            // Size: 7, Type: INT, Flags: PRIVATE, OWNER
    eUnitFieldPowerCostMultiplier = eObjectEnd + 0x0084,          // Size: 7, Type: FLOAT, Flags: PRIVATE, OWNER
    eUnitFieldMaxhealthmodifier = eObjectEnd + 0x008B,            // Size: 1, Type: FLOAT, Flags: PRIVATE, OWNER
    eUnitFieldHoverheight = eObjectEnd + 0x008C,                  // Size: 1, Type: FLOAT, Flags: PUBLIC
    eUnitFieldPadding = eObjectEnd + 0x008D,                      // Size: 1, Type: INT, Flags: NONE
    eUnitEnd = eObjectEnd + 0x008E,
    ePlayerDuelArbiter = eUnitEnd + 0x0000,                       // Size: 2, Type: LONG, Flags: PUBLIC
    ePlayerFlags = eUnitEnd + 0x0002,                             // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerGuildid = eUnitEnd + 0x0003,                           // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerGuildrank = eUnitEnd + 0x0004,                         // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerBytes = eUnitEnd + 0x0005,                             // Size: 1, Type: BYTES, Flags: PUBLIC
    ePlayerBytes2 = eUnitEnd + 0x0006,                            // Size: 1, Type: BYTES, Flags: PUBLIC
    ePlayerBytes3 = eUnitEnd + 0x0007,                            // Size: 1, Type: BYTES, Flags: PUBLIC
    ePlayerDuelTeam = eUnitEnd + 0x0008,                          // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerGuildTimestamp = eUnitEnd + 0x0009,                    // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerQuestLog11 = eUnitEnd + 0x000A,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog12 = eUnitEnd + 0x000B,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog13 = eUnitEnd + 0x000C,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog14 = eUnitEnd + 0x000E,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog21 = eUnitEnd + 0x000F,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog22 = eUnitEnd + 0x0010,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog23 = eUnitEnd + 0x0011,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog25 = eUnitEnd + 0x0013,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog31 = eUnitEnd + 0x0014,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog32 = eUnitEnd + 0x0015,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog33 = eUnitEnd + 0x0016,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog35 = eUnitEnd + 0x0018,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog41 = eUnitEnd + 0x0019,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog42 = eUnitEnd + 0x001A,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog43 = eUnitEnd + 0x001B,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog45 = eUnitEnd + 0x001D,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog51 = eUnitEnd + 0x001E,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog52 = eUnitEnd + 0x001F,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog53 = eUnitEnd + 0x0020,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog55 = eUnitEnd + 0x0022,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog61 = eUnitEnd + 0x0023,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog62 = eUnitEnd + 0x0024,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog63 = eUnitEnd + 0x0025,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog65 = eUnitEnd + 0x0027,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog71 = eUnitEnd + 0x0028,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog72 = eUnitEnd + 0x0029,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog73 = eUnitEnd + 0x002A,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog75 = eUnitEnd + 0x002C,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog81 = eUnitEnd + 0x002D,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog82 = eUnitEnd + 0x002E,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog83 = eUnitEnd + 0x002F,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog85 = eUnitEnd + 0x0031,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog91 = eUnitEnd + 0x0032,                        // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog92 = eUnitEnd + 0x0033,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog93 = eUnitEnd + 0x0034,                        // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog95 = eUnitEnd + 0x0036,                        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog101 = eUnitEnd + 0x0037,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog102 = eUnitEnd + 0x0038,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog103 = eUnitEnd + 0x0039,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog105 = eUnitEnd + 0x003B,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog111 = eUnitEnd + 0x003C,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog112 = eUnitEnd + 0x003D,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog113 = eUnitEnd + 0x003E,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog115 = eUnitEnd + 0x0040,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog121 = eUnitEnd + 0x0041,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog122 = eUnitEnd + 0x0042,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog123 = eUnitEnd + 0x0043,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog125 = eUnitEnd + 0x0045,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog131 = eUnitEnd + 0x0046,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog132 = eUnitEnd + 0x0047,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog133 = eUnitEnd + 0x0048,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog135 = eUnitEnd + 0x004A,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog141 = eUnitEnd + 0x004B,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog142 = eUnitEnd + 0x004C,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog143 = eUnitEnd + 0x004D,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog145 = eUnitEnd + 0x004F,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog151 = eUnitEnd + 0x0050,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog152 = eUnitEnd + 0x0051,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog153 = eUnitEnd + 0x0052,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog155 = eUnitEnd + 0x0054,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog161 = eUnitEnd + 0x0055,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog162 = eUnitEnd + 0x0056,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog163 = eUnitEnd + 0x0057,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog165 = eUnitEnd + 0x0059,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog171 = eUnitEnd + 0x005A,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog172 = eUnitEnd + 0x005B,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog173 = eUnitEnd + 0x005C,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog175 = eUnitEnd + 0x005E,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog181 = eUnitEnd + 0x005F,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog182 = eUnitEnd + 0x0060,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog183 = eUnitEnd + 0x0061,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog185 = eUnitEnd + 0x0063,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog191 = eUnitEnd + 0x0064,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog192 = eUnitEnd + 0x0065,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog193 = eUnitEnd + 0x0066,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog195 = eUnitEnd + 0x0068,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog201 = eUnitEnd + 0x0069,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog202 = eUnitEnd + 0x006A,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog203 = eUnitEnd + 0x006B,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog205 = eUnitEnd + 0x006D,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog211 = eUnitEnd + 0x006E,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog212 = eUnitEnd + 0x006F,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog213 = eUnitEnd + 0x0070,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog215 = eUnitEnd + 0x0072,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog221 = eUnitEnd + 0x0073,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog222 = eUnitEnd + 0x0074,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog223 = eUnitEnd + 0x0075,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog225 = eUnitEnd + 0x0077,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog231 = eUnitEnd + 0x0078,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog232 = eUnitEnd + 0x0079,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog233 = eUnitEnd + 0x007A,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog235 = eUnitEnd + 0x007C,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog241 = eUnitEnd + 0x007D,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog242 = eUnitEnd + 0x007E,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog243 = eUnitEnd + 0x007F,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog245 = eUnitEnd + 0x0081,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog251 = eUnitEnd + 0x0082,                       // Size: 1, Type: INT, Flags: PARTY_MEMBER
    ePlayerQuestLog252 = eUnitEnd + 0x0083,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerQuestLog253 = eUnitEnd + 0x0084,                       // Size: 2, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerQuestLog255 = eUnitEnd + 0x0086,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerVisibleItem1Entryid = eUnitEnd + 0x0087,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem1Enchantment = eUnitEnd + 0x0088,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem2Entryid = eUnitEnd + 0x0089,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem2Enchantment = eUnitEnd + 0x008A,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem3Entryid = eUnitEnd + 0x008B,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem3Enchantment = eUnitEnd + 0x008C,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem4Entryid = eUnitEnd + 0x008D,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem4Enchantment = eUnitEnd + 0x008E,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem5Entryid = eUnitEnd + 0x008F,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem5Enchantment = eUnitEnd + 0x0090,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem6Entryid = eUnitEnd + 0x0091,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem6Enchantment = eUnitEnd + 0x0092,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem7Entryid = eUnitEnd + 0x0093,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem7Enchantment = eUnitEnd + 0x0094,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem8Entryid = eUnitEnd + 0x0095,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem8Enchantment = eUnitEnd + 0x0096,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem9Entryid = eUnitEnd + 0x0097,               // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem9Enchantment = eUnitEnd + 0x0098,           // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem10Entryid = eUnitEnd + 0x0099,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem10Enchantment = eUnitEnd + 0x009A,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem11Entryid = eUnitEnd + 0x009B,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem11Enchantment = eUnitEnd + 0x009C,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem12Entryid = eUnitEnd + 0x009D,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem12Enchantment = eUnitEnd + 0x009E,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem13Entryid = eUnitEnd + 0x009F,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem13Enchantment = eUnitEnd + 0x00A0,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem14Entryid = eUnitEnd + 0x00A1,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem14Enchantment = eUnitEnd + 0x00A2,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem15Entryid = eUnitEnd + 0x00A3,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem15Enchantment = eUnitEnd + 0x00A4,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem16Entryid = eUnitEnd + 0x00A5,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem16Enchantment = eUnitEnd + 0x00A6,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem17Entryid = eUnitEnd + 0x00A7,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem17Enchantment = eUnitEnd + 0x00A8,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem18Entryid = eUnitEnd + 0x00A9,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem18Enchantment = eUnitEnd + 0x00AA,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerVisibleItem19Entryid = eUnitEnd + 0x00AB,              // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerVisibleItem19Enchantment = eUnitEnd + 0x00AC,          // Size: 1, Type: TWO_SHORT, Flags: PUBLIC
    ePlayerChosenTitle = eUnitEnd + 0x00AD,                       // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerFakeInebriation = eUnitEnd + 0x00AE,                   // Size: 1, Type: INT, Flags: PUBLIC
    ePlayerFieldPad0 = eUnitEnd + 0x00AF,                         // Size: 1, Type: INT, Flags: NONE
    ePlayerFieldInvSlotHead = eUnitEnd + 0x00B0,                  // Size: 46, Type: LONG, Flags: PRIVATE
    ePlayerFieldPackSlot1 = eUnitEnd + 0x00DE,                    // Size: 32, Type: LONG, Flags: PRIVATE
    ePlayerFieldBankSlot1 = eUnitEnd + 0x00FE,                    // Size: 56, Type: LONG, Flags: PRIVATE
    ePlayerFieldBankbagSlot1 = eUnitEnd + 0x0136,                 // Size: 14, Type: LONG, Flags: PRIVATE
    ePlayerFieldVendorbuybackSlot1 = eUnitEnd + 0x0144,           // Size: 24, Type: LONG, Flags: PRIVATE
    ePlayerFieldKeyringSlot1 = eUnitEnd + 0x015C,                 // Size: 64, Type: LONG, Flags: PRIVATE
    ePlayerFieldCurrencytokenSlot1 = eUnitEnd + 0x019C,           // Size: 64, Type: LONG, Flags: PRIVATE
    ePlayerFarsight = eUnitEnd + 0x01DC,                          // Size: 2, Type: LONG, Flags: PRIVATE
    ePlayerFieldKnownTitles = eUnitEnd + 0x01DE,                  // Size: 2, Type: LONG, Flags: PRIVATE
    ePlayerFieldKnownTitleS1 = eUnitEnd + 0x01E0,                 // Size: 2, Type: LONG, Flags: PRIVATE
    ePlayerFieldKnownTitleS2 = eUnitEnd + 0x01E2,                 // Size: 2, Type: LONG, Flags: PRIVATE
    ePlayerFieldKnownCurrencies = eUnitEnd + 0x01E4,              // Size: 2, Type: LONG, Flags: PRIVATE
    ePlayerXp = eUnitEnd + 0x01E6,                                // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerNextLevelXp = eUnitEnd + 0x01E7,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerSkillInfo11 = eUnitEnd + 0x01E8,                       // Size: 384, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerCharacterPointS1 = eUnitEnd + 0x0368,                  // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerCharacterPointS2 = eUnitEnd + 0x0369,                  // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerTrackCreatures = eUnitEnd + 0x036A,                    // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerTrackResources = eUnitEnd + 0x036B,                    // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerBlockPercentage = eUnitEnd + 0x036C,                   // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerDodgePercentage = eUnitEnd + 0x036D,                   // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerParryPercentage = eUnitEnd + 0x036E,                   // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerExpertise = eUnitEnd + 0x036F,                         // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerOffhandExpertise = eUnitEnd + 0x0370,                  // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerCritPercentage = eUnitEnd + 0x0371,                    // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerRangedCritPercentage = eUnitEnd + 0x0372,              // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerOffhandCritPercentage = eUnitEnd + 0x0373,             // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerSpellCritPercentagE1 = eUnitEnd + 0x0374,              // Size: 7, Type: FLOAT, Flags: PRIVATE
    ePlayerShieldBlock = eUnitEnd + 0x037B,                       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerShieldBlockCritPercentage = eUnitEnd + 0x037C,         // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerExploredZones1 = eUnitEnd + 0x037D,                    // Size: 128, Type: BYTES, Flags: PRIVATE
    ePlayerRestStateExperience = eUnitEnd + 0x03FD,               // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldCoinage = eUnitEnd + 0x03FE,                      // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldModDamageDonePos = eUnitEnd + 0x03FF,             // Size: 7, Type: INT, Flags: PRIVATE
    ePlayerFieldModDamageDoneNeg = eUnitEnd + 0x0406,             // Size: 7, Type: INT, Flags: PRIVATE
    ePlayerFieldModDamageDonePct = eUnitEnd + 0x040D,             // Size: 7, Type: INT, Flags: PRIVATE
    ePlayerFieldModHealingDonePos = eUnitEnd + 0x0414,            // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldModHealingPct = eUnitEnd + 0x0415,                // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerFieldModHealingDonePct = eUnitEnd + 0x0416,            // Size: 1, Type: FLOAT, Flags: PRIVATE
    ePlayerFieldModTargetResistance = eUnitEnd + 0x0417,          // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldModTargetPhysicalResistance = eUnitEnd + 0x0418,  // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldBytes = eUnitEnd + 0x0419,                        // Size: 1, Type: BYTES, Flags: PRIVATE
    ePlayerAmmoId = eUnitEnd + 0x041A,                            // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerSelfResSpell = eUnitEnd + 0x041B,                      // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldPvpMedals = eUnitEnd + 0x041C,                    // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldBuybackPrice1 = eUnitEnd + 0x041D,                // Size: 12, Type: INT, Flags: PRIVATE
    ePlayerFieldBuybackTimestamp1 = eUnitEnd + 0x0429,            // Size: 12, Type: INT, Flags: PRIVATE
    ePlayerFieldKills = eUnitEnd + 0x0435,                        // Size: 1, Type: TWO_SHORT, Flags: PRIVATE
    ePlayerFieldTodayContribution = eUnitEnd + 0x0436,            // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldYesterdayContribution = eUnitEnd + 0x0437,        // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldLifetimeHonorbaleKills = eUnitEnd + 0x0438,       // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldByteS2 = eUnitEnd + 0x0439,                       // Size: 1, Type: 6, Flags: PRIVATE
    ePlayerFieldWatchedFactionIndex = eUnitEnd + 0x043A,          // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldCombatRating1 = eUnitEnd + 0x043B,                // Size: 25, Type: INT, Flags: PRIVATE
    ePlayerFieldArenaTeamInfo11 = eUnitEnd + 0x0454,              // Size: 21, Type: INT, Flags: PRIVATE
    ePlayerFieldHonorCurrency = eUnitEnd + 0x0469,                // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldArenaCurrency = eUnitEnd + 0x046A,                // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldMaxLevel = eUnitEnd + 0x046B,                     // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerFieldDailyQuests1 = eUnitEnd + 0x046C,                 // Size: 25, Type: INT, Flags: PRIVATE
    ePlayerRuneRegen1 = eUnitEnd + 0x0485,                        // Size: 4, Type: FLOAT, Flags: PRIVATE
    ePlayerNoReagentCost1 = eUnitEnd + 0x0489,                    // Size: 3, Type: INT, Flags: PRIVATE
    ePlayerFieldGlyphSlots1 = eUnitEnd + 0x048C,                  // Size: 6, Type: INT, Flags: PRIVATE
    ePlayerFieldGlyphs1 = eUnitEnd + 0x0492,                      // Size: 6, Type: INT, Flags: PRIVATE
    ePlayerGlyphsEnabled = eUnitEnd + 0x0498,                     // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerPetSpellPower = eUnitEnd + 0x0499,                     // Size: 1, Type: INT, Flags: PRIVATE
    ePlayerEnd = eUnitEnd + 0x049A,
};

enum GameObjectFields {
    eObjectFieldCreatedBy = eObjectEnd + 0x0000,      // Size: 2, Type: LONG, Flags: PUBLIC
    eGameobjectDisplayid = eObjectEnd + 0x0002,       // Size: 1, Type: INT, Flags: PUBLIC
    eGameobjectFlags = eObjectEnd + 0x0003,           // Size: 1, Type: INT, Flags: PUBLIC
    eGameobjectParentrotation = eObjectEnd + 0x0004,  // Size: 4, Type: FLOAT, Flags: PUBLIC
    eGameobjectDynamic = eObjectEnd + 0x0008,         // Size: 1, Type: TWO_SHORT, Flags: DYNAMIC
    eGameobjectFaction = eObjectEnd + 0x0009,         // Size: 1, Type: INT, Flags: PUBLIC
    eGameobjectLevel = eObjectEnd + 0x000A,           // Size: 1, Type: INT, Flags: PUBLIC
    eGameobjectBytes1 = eObjectEnd + 0x000B,          // Size: 1, Type: BYTES, Flags: PUBLIC
    eGameobjectEnd = eObjectEnd + 0x000C,
};

enum DynamicObjectFields {
    eDynamicobjectCaster = eObjectEnd + 0x0000,    // Size: 2, Type: LONG, Flags: PUBLIC
    eDynamicobjectBytes = eObjectEnd + 0x0002,     // Size: 1, Type: BYTES, Flags: PUBLIC
    eDynamicobjectSpellid = eObjectEnd + 0x0003,   // Size: 1, Type: INT, Flags: PUBLIC
    eDynamicobjectRadius = eObjectEnd + 0x0004,    // Size: 1, Type: FLOAT, Flags: PUBLIC
    eDynamicobjectCasttime = eObjectEnd + 0x0005,  // Size: 1, Type: INT, Flags: PUBLIC
    eDynamicobjectEnd = eObjectEnd + 0x0006,
};

enum CorpseFields {
    eCorpseFieldOwner = eObjectEnd + 0x0000,         // Size: 2, Type: LONG, Flags: PUBLIC
    eCorpseFieldParty = eObjectEnd + 0x0002,         // Size: 2, Type: LONG, Flags: PUBLIC
    eCorpseFieldDisplayId = eObjectEnd + 0x0004,     // Size: 1, Type: INT, Flags: PUBLIC
    eCorpseFieldItem = eObjectEnd + 0x0005,          // Size: 19, Type: INT, Flags: PUBLIC
    eCorpseFieldBytes1 = eObjectEnd + 0x0018,        // Size: 1, Type: BYTES, Flags: PUBLIC
    eCorpseFieldBytes2 = eObjectEnd + 0x0019,        // Size: 1, Type: BYTES, Flags: PUBLIC
    eCorpseFieldGuild = eObjectEnd + 0x001A,         // Size: 1, Type: INT, Flags: PUBLIC
    eCorpseFieldFlags = eObjectEnd + 0x001B,         // Size: 1, Type: INT, Flags: PUBLIC
    eCorpseFieldDynamicFlags = eObjectEnd + 0x001C,  // Size: 1, Type: INT, Flags: DYNAMIC
    eCorpseFieldPad = eObjectEnd + 0x001D,           // Size: 1, Type: INT, Flags: NONE
    eCorpseEnd = eObjectEnd + 0x001E,
};
